### PR TITLE
Wp api v2

### PR DESCRIPTION
**Pull request by foxpaul**
* Supports the WP-API v2
* /menu/<id> endpoint returns a nested menu structure

### CODE REVIEW

**Comment by nekojira** [comment]
Hey @foxpaul  this is cool - I didn't have time recently to work at the menus plugin and I knew that v2 should be supported

I have only a question though, how about v1 support? I think there are still folks using the old WP API plugin - at first glance I saw you changed some methods and actions to reflect new hooks introduced in v2, but you deleted old methods - I wanted to look at a solution that would support both v1 and v2, what do you think?

**Comment by foxpaul** [comment]
Hi @nekojira yeah you're right - no v1 support here, although it wouldn't be *too* hard to support both in 1 branch, i'm not sure that's the right way(?) 

I was thinking of keeping the v1 and v2 branches separate (v1 eventually becoming 'legacy').

**Comment by nekojira** [comment]
I see what you mean, but we should push this on wordpress.org plugin directory as well - there's no branch control for people adding this as a normal WordPress plugin

I didn't catch up with latest changes in WP REST API documentation - if it's everything done via hooks, and the hooks have changed, I suppose one could simply hook different methods to those different hooks and both v1/v2 would be supported

but if it's not the case, and there's no way to support _both_ at the same time, then I'd go with your idea of keeping two branches

**Comment by foxpaul** [comment]
ah yeah, the hooks have changed. 
v1 uses `json_api_init`, v2 uses `rest_api_init` - will look into it more later.

**Comment by Sjeiti** [comment]
Good addition. One thing that might be smart to change is the namespace. The current namespace is 'wp/v2/menus/' but from the [v2 docs](http://v2.wp-api.org/extending/adding/#namespacing) it seems good practice to use the plugin name as a prefix. So that would be something like 'menus/v1/etc'. The wp-api authors might claim 'wp/v2/menus' for future versions (wp-rest-api v2 is still unstable and this looks like default functionality to me).

**Pull request merged**
