### PR TITLE
Support for ACF

### PR DESCRIPTION
**Pull request by rubenCodeforges**

### CODE REVIEW

**Comment by nekojira** [comment]
Hi @rubenCodeforges! Thanks for contributing to WP API Menus. Could you explain to me what the modifications would do? What exactly Advanced Custom Fields would do with menus? I think not everybody has ACF plugin installed and perhaps not everyone would use it in the same way. Therefore this could be too specific to incorporate in WP API Menus. Also, one could use 'json_menus_format_menu_item' hook to filter the menu output. If you think there should be room for another hook somewhere else we might add it if it's beneficial to more than a single or too specific use case. Thanks

**Comment by rubenCodeforges** [comment]
Hi it will add just a field to response json "acf" if post have acf the data will be added there .
Yes perhaps i should create a check for acf or add it like parameter so if some one needs it he can turn we know that acf is widly used by devs , and api plugins is mostly for dev and not for users , thats wy i think it could be usefull here

**Comment by rubenCodeforges** [comment]
anyway if you dont need this just cancel ive added my modified fork to composer so i can use the fork

**Comment by nekojira** [comment]
Well sure, I use ACF myself, but what kind of data/fields should return in the menus? Also, there are a lot of plugins that play with meta fields - Types, Pods, many others... Adding support for each single of them would pollute the plugin. That's why I think the job should be done with hooks for filters. 

If you think there's need for another we could add it. Right now you can take 'json_menus_format_menu_item' and alter the menu structure with PHP in your theme or plugin. If it's not practical we can add one more hook where it would be needed.

**Comment by rubenCodeforges** [comment]
ok thanks ill try it out

**Pull request closed without merging**
